name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:
    branches:
      - main
    types:
      - closed


jobs:

  wheels_on_PR:
    if: ${{ github.event.pull_request.merged == true }}
    name: ${{ matrix.py }} ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        arch: [native]
        py: [cp313]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - name: Setup gfortran for Linux
        uses: awvwgk/setup-fortran@main
        id: setup-fortran
        with:
          compiler: gcc
          version: 13

      - name: cibuildwheel on Linux
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: ${{ matrix.py }}-*
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_ENVIRONMENT_PASS_LINUX: CI
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl



  wheels:
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/v') }}
    name: ${{ matrix.py }} ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]
        arch: [auto64, aarch64]
        py: [cp39, cp310, cp311, cp312, cp313]
        exclude:
          - os: windows-latest
            arch: aarch64
          - os: macos-13
            arch: aarch64
          - os: macos-14
            arch: aarch64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get latest CMake and Ninja
        uses: lukka/get-cmake@latest

      - if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v2

      # # Remove after January 16th 2023 when GA switches to 14.2 by default
      # # Remove someday when migration for all nodes will be finished
      # - if: ${{ matrix.os == 'macos-latest' }}
      #   run: sudo xcode-select -s "/Applications/Xcode_14.2.app"

      # - if: ${{ matrix.os == 'macos-latest' &&  matrix.arch == 'native'}}
      #   name: Install graphviz for tests on MacOS native
      #   uses: tlylt/install-graphviz@v1

      - uses: ts-graphviz/setup-graphviz@v1

      # - if: ${{ matrix.os == 'macos-latest' &&  matrix.arch == 'native'}}
      #   name: Setup gfortran for MacOS native
      #   run: |
      #     # Taken from https://github.com/numpy/numpy/tree/main/tools/wheels
      #     set -xe
      #     chmod +x .github/workflows/gfortran_utils.sh
      #     source .github/workflows/gfortran_utils.sh
      #     install_gfortran
      #     gfortran --version
      #     which gfortran

      - name: Setup gfortran
        uses: awvwgk/setup-fortran@v1.6.1
        id: setup-fortran
        with:
          compiler: gcc
          version: 13

      - if: ${{ matrix.os == 'windows-latest' }}
        name: cibuildwheel on Windows
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: ${{ matrix.py }}-*
          CIBW_ARCHS: ${{ matrix.arch }}
          CMAKE_GENERATOR: "MinGW Makefiles"
          FC: ${{ steps.setup-fortran.outputs.fc }}

      - if: ${{ matrix.os == 'ubuntu-latest' }}
        name: cibuildwheel on Linux
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: ${{ matrix.py }}-*
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_ENVIRONMENT_PASS_LINUX: CI
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014

      - if: ${{ matrix.os == 'macos-13' ||  matrix.os == 'macos-14' }}
        name: cibuildwheel on MacOS
        uses: pypa/cibuildwheel@v2.21.3
        env:
          CIBW_BUILD: ${{ matrix.py }}-*
          CIBW_ARCHS: ${{ matrix.arch }}
          no_proxy: '*'

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  sdist:
    name: source package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'

      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: '3.12'

      - uses: tlylt/install-graphviz@v1

      - run: python -m pip install --upgrade pip wheel setuptools
      - run: pipx run build --sdist
      - run: python -m pip install --prefer-binary -v `echo dist/chromo-*`[test]
      - run: python -m pytest -v

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz

  upload_to_PyPI:
    name: Upload to PyPI
    needs: [wheels, sdist]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    steps:
      - name: Download files in artifact to "dist/" directory
        uses: actions/download-artifact@v4.1.7
        with:
          name: artifact
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1.8
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}


